sandboxnu/sandboxneu.com

src/content/mission/mission.json

Wrote up some stuff about our values inside the Mission section. Would like some feedback on if we agree on this portrayal of the club. Is this how we want people to picture us? Does the wording cast us in the best light?

Replaced Bob Ross ipsum with real copy

---

README.md

I figured with all of us committing all the time, it's probably a good idea to update this so people have something nicer to see when they land on this page. Let me know if you have suggestions for things to add.

Update from Gatsby default README

---

now.json

Merging this should publish the site to `sandboxneu.com`
Not ready yet

publish to sandboxneu.com

---

gatsby-config.js
src/components/IndexPage/hero.js
src/components/layout.js
src/components/nav.js

This PR adds animations that I think look sleek and professional to the hero page. Since I don't think the design of the homepage is all too impressive, hopefully this will add another dimension to it to keep it interesting.

Animate hero

---

gatsby-node.js
src/components/ApplyPage/ApplyContent.js
src/content/apply/design.md
src/content/apply/developer.md
src/content/apply/devops.md
src/templates/apply.js

IDK about the subtitle on the apply page at all anymore, lmk what you think
Also I need the mailchimp link lol idk what happened but i scoured the Slack and couldn't find it, just send it over when you see this

Close applications

---

src/components/countdown.js
src/templates/apply.js

This is a very temporary hacky PR so that people don't end up at the page with outdated information. Eventually, we should clean up this code and make it a switch so we can show the content we need to do or show a countdown.

Hacky update to change the apply page to add a countdown

---

src/content/apply/designer.md
src/content/apply/developer.md

close application

---

src/content/hero/hero.json

Changes title from the previous mission statement to the current one.

Change landing page's tagline

---

src/content/who/who.json

remove research-specific language from the 'who' section

---

src/components/ApplyPage/position.js
src/components/ApplyPage/showcase.js
src/components/ApplyPage/values.js
src/content/apply/developer.md
src/pages/apply.js

and also fixed some styles on mobile :)

added in developer info to publish when open

---

src/components/IndexPage/who.js
src/styles/components/Header.js

styling tweaks

---

src/components/accordion.js
src/components/faqs.js
src/styles/colors.js

Added a new component Accordion for FAQs. The styling is not exactly the same as what Catherine suggested, so I might ask her about it later.

Faq styling

---

src/components/IndexPage/hero.js
src/components/emailSubscription.js
src/content/hero/hero.json
src/pages/index.js

Hero styling

---

src/components/IndexPage/info.js
src/components/PageLayout/nav.js
src/components/card.js
src/pages/index.js
src/styles/components/Header.js

- added new button styles based on mockup
- removed values from index page

New button

---

src/components/ApplyPage/showcase.js

changed youtube link to promotional video

---

src/components/PageLayout/nav.js

highlight text for nav bar

---

src/components/AboutPage/getInvolved.js
src/components/AboutPage/infoCard.js
src/components/PageLayout/nav.js
src/content/getInvolvedCards/getInvolvedCards.json
src/pages/about.js

desktop and mobile for get involved section in about page

Get involved

---

src/components/AboutPage/getInvolved.js
src/pages/about.js
src/styles/components/Banner.js

about page banner. Kinda ditched the quotation mark in mobile cuz it's mad hard to position. I think it's fine to just get rid of it...

about page banner

---

src/components/IndexPage/info.js
src/components/card.js
src/styles/components/Banner.js

- mobile card styles
- fixed banner issue on mobile

Index mobile

---

src/components/AboutPage/getInvolved.js
src/components/AboutPage/infoCard.js
src/components/AboutPage/values.js
src/components/ApplyPage/heading.js
src/components/ApplyPage/position.js
src/components/ApplyPage/values.js
src/components/IndexPage/info.js
src/components/IndexPage/marketing.js
src/components/PageLayout/footer.js
src/components/TeamPage/teamPhotos.js
src/content/infoCards/infoCards.json
src/pages/apply.js
src/pages/team.js

these are some tweaks I did across pages to update fonts colors and fix some margins + add in animation to the about page

Content cleanup

---

src/pages/about.js

styling tweak

---

src/content/portfolio/projects.json

work with us

---

src/components/IndexPage/hero.js
src/components/IndexPage/marketing.js
src/content/marketing/marketing.json
src/pages/index.js

added in a section to highlight our latest youtube video

Youtube section

---

src/components/AboutPage/values.js

Northeastern should be capitalized

uppercase Northeastern

---

src/components/RolePage/RoleContent.js
src/content/apply/brand-designer.md
src/content/apply/developer.md
src/content/apply/oasis.md

added in page for oasis application

add in oasis

---

src/content/apply/apply.json
src/content/apply/developer.md
src/content/apply/ux-designer.md

EP - open apps for fall 2021

---

src/content/apply/brand-designer.md
src/content/apply/ux-designer.md

EP - open designer apps

---

src/content/apply/developer.md

developer experience link

---

gatsby-node.js
yarn.lock

Kept running into problem with `window undefined` in `amplitude-js` when trying to set up dev environment. Did some googling and found this [link](https://www.gatsbyjs.com/docs/debugging-html-builds/) for fixing the problem.

Fix Bug With Amplitude-JS

---

src/content/apply/apply.json
src/content/apply/brand-designer.md
src/content/apply/developer.md
src/content/apply/oasis.md
src/content/apply/ux-designer.md
src/pages/about.js
src/pages/index.js

Closed all applications and specified when Spring 2022 applications open for developers

Close All Applications

---

src/components/PageLayout/footer.js
src/content/apply/apply.json
src/content/apply/developer.md

Open Dev Apps for Spring 2022

---

src/content/clients/clients.json

Data-only changes, just simple updates to the site so that clients still applying for the summer aren't confused
I was gonna do this yesterday on the bus but I fell asleep instead 😭

Update client page info for Spring/Summer 2023 project applications

---

src/content/apply/apply.json
src/pages/about.js
src/pages/index.js

Updated site to reflect apps close

Apps are now closed for Fall 2024

---

src/content/apply/apply.json
src/content/apply/brand-designer.md
src/content/apply/developer.md
src/content/apply/ux-designer.md
src/content/faqs/faqs.json
src/pages/about.js
src/pages/index.js

**Spring 2025 Application Update**

Open Applications for Spring 2025

---

now.json

Forgot to update the How We Recruit links at the bottom of the `/apply` page 😳

Update How We Recruit Links for Spring 2025

---

src/content/apply/developer.md

Previous Link: [https://info.khouryofficehours.com/](https://info.khouryofficehours.com/) (probably shouldn't click very sus)
New Link: [https://officehours.khoury.northeastern.edu/](https://officehours.khoury.northeastern.edu/)

Fix Khoury Office Hours Link

---

src/content/apply/brand-designer.md
src/content/apply/ux-designer.md
src/content/faqs/faqs.json

Change Designer Application Closing Dates

---

src/content/apply/apply.json
src/content/apply/brand-designer.md
src/content/apply/developer.md
src/content/apply/ux-designer.md
src/content/faqs/faqs.json
src/pages/about.js
src/pages/index.js

Update Locales for F25 Application Cycle

---

src/content/apply/apply.json
src/content/faqs/faqs.json
src/pages/about.js
src/pages/index.js

Update locales for f25 apps closed

---

package.json

updating node in the engine field from greater than = 18 to specefically 22.x to please vercel.

setting node explicitly to 22
